# Generated by Django 4.2.11 on 2025-09-11 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('priv_level', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('experiment_mode', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmnt.project')),
            ],
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('action', models.CharField(default='Unknown', max_length=100)),
                ('entities', models.TextField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmnt.project')),
            ],
        ),
        migrations.CreateModel(
            name='TrustBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('actor_type', models.CharField(max_length=100)),
                ('actor_name', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('entities', models.ManyToManyField(to='tmnt.entity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmnt.project')),
            ],
        ),
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cve_id', models.CharField(max_length=100)),
                ('stride_class', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('assets', models.ManyToManyField(to='tmnt.entity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmnt.project')),
            ],
        ),
        migrations.CreateModel(
            name='MitigatedThreat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='tmnt.entity')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control', to='tmnt.control')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmnt.project')),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threat', to='tmnt.threat')),
            ],
        ),
        migrations.CreateModel(
            name='ExtAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ports', models.CharField(max_length=400)),
                ('machine_type', models.CharField(max_length=100)),
                ('type', models.CharField(default='External Entity', max_length=15)),
                ('parent_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_extasset', to='tmnt.entity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmnt.project')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmnt.project'),
        ),
        migrations.CreateModel(
            name='Datastore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data_type', models.CharField(max_length=100)),
                ('machine_type', models.CharField(max_length=100)),
                ('ports', models.CharField(max_length=400)),
                ('actor', models.ManyToManyField(to='tmnt.actor')),
                ('parent_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_datastore', to='tmnt.entity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmnt.project')),
                ('trust_boundaries', models.ManyToManyField(to='tmnt.trustboundary')),
            ],
        ),
        migrations.CreateModel(
            name='DataFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('protocol', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_entity', to='tmnt.entity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmnt.project')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_entity', to='tmnt.entity')),
            ],
        ),
        migrations.CreateModel(
            name='D3NodePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d3_node_positions', to='tmnt.entity')),
            ],
        ),
        migrations.AddField(
            model_name='control',
            name='assets',
            field=models.ManyToManyField(to='tmnt.entity'),
        ),
        migrations.AddField(
            model_name='control',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmnt.project'),
        ),
        migrations.AddField(
            model_name='control',
            name='threats',
            field=models.ManyToManyField(to='tmnt.threat'),
        ),
        migrations.CreateModel(
            name='Assumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True)),
                ('assets', models.ManyToManyField(to='tmnt.entity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmnt.project')),
                ('threats', models.ManyToManyField(to='tmnt.threat')),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='parent_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_actor', to='tmnt.entity'),
        ),
        migrations.AddField(
            model_name='actor',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmnt.project'),
        ),
        migrations.AddConstraint(
            model_name='trustboundary',
            constraint=models.UniqueConstraint(fields=('name', 'project'), name='tb_name_unique_to_project'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='unique_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='extasset',
            constraint=models.UniqueConstraint(fields=('name', 'project'), name='extasset_name_unique_to_project'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.UniqueConstraint(fields=('name', 'project'), name='entity_name_unique_to_project'),
        ),
        migrations.AddConstraint(
            model_name='actor',
            constraint=models.UniqueConstraint(fields=('name', 'project'), name='actor_name_unique_to_project'),
        ),
    ]
