name: Docker Image CI

on:
  push:
    branches: [deploy]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push UI
        uses: docker/build-push-action@v5
        with:
          context: app/
          file: app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tmnt_ui:latest
      - name: Build and push Controller
        uses: docker/build-push-action@v5
        with:
          context: controller/
          file: controller/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tmnt_controller:latest
